GO CLI: Support pxf cluster migrate
Similar to pxf migrate, pxf cluster migrate helps migrating an old PXF
version to a new PXF version in a cluster.

diff --git a/server/pxf-service/src/scripts/pxf b/server/pxf-service/src/scripts/pxf
--- a/server/pxf-service/src/scripts/pxf
+++ b/server/pxf-service/src/scripts/pxf
@@ -107,6 +107,14 @@ function fail()
     exit 1
 }
 
+# print error message and provide a hint
+function failWithHint()
+{
+    echoRed    "ERROR: $1"
+    echoYellow "HINT:  $2"
+    exit 1
+}
+
 #
 # waitForSpringBoot waits for spring boot to finish loading
 # for given attempts number.
@@ -282,11 +290,7 @@ function doInit()
 function doPrepare()
 {
     # FILE1 -ef FILE2  True if file1 is a hard link to file2.
-    if [[ $PXF_HOME -ef $PXF_BASE ]]; then
-        echoRed    "ERROR: 'pxf [cluster] prepare' requires a \$PXF_BASE value different from your PXF installation directory."
-        echoYellow "HINT:  Use 'PXF_BASE=<YOUR_PXF_BASE_DIRECTORY> pxf [cluster] prepare'."
-        exit 1
-    fi
+    [[ ! $PXF_HOME -ef $PXF_BASE ]] || failWithHint "'pxf [cluster] prepare' requires a \$PXF_BASE value different from your PXF installation directory." "Use 'PXF_BASE=<YOUR_PXF_BASE_DIRECTORY> pxf [cluster] prepare'."
 
     if [[ -d $PXF_BASE ]] && [[ "$(ls -A $PXF_BASE)" ]]; then
         echoRed "ERROR: The \$PXF_BASE ($PXF_BASE) location is not empty."
@@ -314,33 +318,33 @@ function migrateMergeConfiguration()
 function doMigrate()
 {
     # Validate PXF_CONF
-    if [[ -z "$PXF_CONF" ]]; then
-        echoRed    "ERROR: The \$PXF_CONF environment variable is not specified. Specify the \$PXF_CONF location of your old PXF installation"
-        echoYellow "HINT:  Use 'PXF_CONF=<YOUR_PXF_CONF_DIRECTORY> [PXF_BASE=<YOUR_PXF_BASE_DIRECTORY>] pxf [cluster] migrate'."
-        exit 1
-    fi
+    [[ -n "$PXF_CONF" ]] || failWithHint "The \$PXF_CONF environment variable is not specified. Specify the \$PXF_CONF location of your old PXF installation" "Use 'PXF_CONF=<YOUR_PXF_CONF_DIRECTORY> [PXF_BASE=<YOUR_PXF_BASE_DIRECTORY>] pxf [cluster] migrate'."
 
     # Make sure $PXF_CONF/conf/pxf-env.sh is present
-    [[ ! -f "${PXF_CONF}/conf/pxf-env.sh" ]]       && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/conf/pxf-env.sh' file is missing"
+    [[ -f "${PXF_CONF}/conf/pxf-env.sh" ]]       || fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/conf/pxf-env.sh' file is missing"
     # Make sure $PXF_CONF/conf/pxf-profiles.xml is present
-    [[ ! -f "${PXF_CONF}/conf/pxf-profiles.xml" ]] && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/conf/pxf-profiles.xml' file is missing"
-    [[ ! -d "${PXF_CONF}/servers" ]]               && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/servers' directory is missing"
-    [[ ! -d "${PXF_CONF}/lib" ]]                   && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/lib' directory is missing"
-    [[ ! -d "${PXF_CONF}/keytabs" ]]               && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/keytabs' directory is missing"
+    [[ -f "${PXF_CONF}/conf/pxf-profiles.xml" ]] || fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/conf/pxf-profiles.xml' file is missing"
+    [[ -d "${PXF_CONF}/servers" ]]               || fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/servers' directory is missing"
+    [[ -d "${PXF_CONF}/lib" ]]                   || fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/lib' directory is missing"
+    [[ -d "${PXF_CONF}/keytabs" ]]               || fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/keytabs' directory is missing"
+
+    # validate PXF_BASE
+    [[ -d $PXF_BASE ]] || failWithHint "PXF_BASE=$PXF_BASE does not exist" "Prepare PXF_BASE by running: 'PXF_BASE=$PXF_BASE pxf prepare'"
+    [[ -w $PXF_BASE ]] || fail "PXF_BASE=$PXF_BASE is not writable"
 
     # FILE1 -ef FILE2  True if file1 is a hard link to file2.
-    [[ "$PXF_CONF" -ef "$PXF_BASE" ]] && fail "The \$PXF_CONF directory must be different from your target directory '$PXF_BASE'"
+    [[ ! "$PXF_CONF" -ef "$PXF_BASE" ]] || fail "The PXF_CONF directory must be different from your target directory '$PXF_BASE'"
 
     # Validate PXF_BASE
-    [[ ! -f "${PXF_BASE}/conf/pxf-env.sh" ]]                 && fail "Invalid \$PXF_BASE location. The '${PXF_BASE}/conf/pxf-env.sh' file is missing"
-    [[ ! -f "${PXF_BASE}/conf/pxf-application.properties" ]] && fail "Invalid \$PXF_BASE location. The '${PXF_BASE}/conf/pxf-application.properties' file is missing"
-    [[ ! -f "${PXF_BASE}/conf/pxf-log4j2.xml" ]]             && fail "Invalid \$PXF_BASE location. The '${PXF_BASE}/conf/pxf-log4j2.xml' file is missing"
+    [[ -f "${PXF_BASE}/conf/pxf-env.sh" ]]                 || failWithHint "The '${PXF_BASE}/conf/pxf-env.sh' file is missing" "Prepare PXF_BASE by running: 'PXF_BASE=$PXF_BASE pxf prepare'"
+    [[ -f "${PXF_BASE}/conf/pxf-application.properties" ]] || failWithHint "The '${PXF_BASE}/conf/pxf-application.properties' file is missing" "Prepare PXF_BASE by running: 'PXF_BASE=$PXF_BASE pxf prepare'"
+    [[ -f "${PXF_BASE}/conf/pxf-log4j2.xml" ]]             || failWithHint "The '${PXF_BASE}/conf/pxf-log4j2.xml' file is missing" "Prepare PXF_BASE by running: 'PXF_BASE=$PXF_BASE pxf prepare'"
 
     echoGreen ""
-    echoGreen "Starting \$PXF_CONF migration from '${PXF_CONF}' to '${PXF_BASE}'"
-    echoGreen "Copying the pxf-profiles.xml file to '${PXF_BASE}/conf'"
+    echoGreen "Starting PXF configuration migration from PXF_CONF='${PXF_CONF}' to PXF_BASE='${PXF_BASE}'"
+    echoGreen "Copying '${PXF_CONF}/conf/pxf-profiles.xml' file to '${PXF_BASE}/conf'"
     cp -L "${PXF_CONF}/conf/pxf-profiles.xml" "${PXF_BASE}/conf"
-    echoGreen "Copying the servers, lib, and keytabs directories to '${PXF_BASE}'"
+    echoGreen "Copying servers, lib, and keytabs directories from '${PXF_CONF}' to '${PXF_BASE}'"
     cp -LR "${PXF_CONF}/servers" "${PXF_CONF}/lib" "${PXF_CONF}/keytabs" "${PXF_BASE}"
     echoGreen "Merging values from '${PXF_CONF}/conf/pxf-env.sh' to '${PXF_BASE}/conf/pxf-application.properties' and '${PXF_BASE}/conf/pxf-env.sh'"
     migrateMergeConfiguration
