CLI: Implement pxf migrate command
Implement the pxf migrate command that allows migration of older
versions of PXF into a new installation of PXF. For example, for PXF
versions prior to 6.0, PXF used a configuration property called PXF_CONF
to specify a directory where PXF configurations are stored.

Now, PXF configurations live under PXF_HOME, this configuration
directory can be relocated to a different location. The base location
for configurations in PXF has been renamed to PXF_BASE.

Migration of PXF_CONF to PXF_BASE is enabled by the pxf migrate command
which does the following:
- Copies the $PXF_CONF/conf/pxf-profiles.xml file to $PXF_BASE/conf/pxf-profiles.xml
- Copies the $PXF_CONF/{servers,lib,keytabs} directories to $PXF_BASE
- Merges values of $PXF_CONF/conf/pxf-env.sh into two different files
  (depending on the property), the two files are
  ${PXF_BASE}/conf/pxf-application.properties and
  ${PXF_BASE}/conf/pxf-env.sh

The pxf migrate utility requires that PXF_CONF is different than
PXF_BASE. The pxf migrate utility validates that the PXF_CONF and
PXF_BASE directories are valid directories.

diff --git a/server/pxf-service/src/scripts/pxf b/server/pxf-service/src/scripts/pxf
--- a/server/pxf-service/src/scripts/pxf
+++ b/server/pxf-service/src/scripts/pxf
@@ -216,6 +216,7 @@ doHelp() {
 	  prepare             prepares a new base directory specified by the \$PXF_BASE environment variable.
 	                      It creates the servers, logs, lib, keytabs, and run directories inside \$PXF_BASE
 	                      and copies configuration files.
+	  migrate             migrates configurations from older installations of PXF
 	  cluster <command>   perform <command> on all the segment hosts in the cluster; try ${bold}pxf cluster help$normal
 
 	  sync <hostname>     synchronize \$PXF_BASE/{conf,lib,servers} directories onto <hostname>. Use --delete to delete extraneous remote files
@@ -277,10 +278,11 @@ function doInit()
     installExternalTableExtension || return 1
 }
 
-# doPrepare changes the PXF_BASE outside of PXF_HOME
+# doPrepare prepares PXF_BASE outside of PXF_HOME
 function doPrepare()
 {
-    if [[ $PXF_HOME == $PXF_BASE ]]; then
+    # FILE1 -ef FILE2  True if file1 is a hard link to file2.
+    if [[ $PXF_HOME -ef $PXF_BASE ]]; then
         echoRed    "ERROR: 'pxf [cluster] prepare' requires a \$PXF_BASE value different from your PXF installation directory."
         echoYellow "HINT:  Use 'PXF_BASE=<YOUR_PXF_BASE_DIRECTORY> pxf [cluster] prepare'."
         exit 1
@@ -300,6 +302,50 @@ function doPrepare()
     echoGreen "PXF configurations and runtime have been created under '$PXF_BASE'"
     echoGreen "Ensure you run PXF commands with the \$PXF_BASE environment set to '$PXF_BASE'"
     echoGreen "Consider adding PXF_BASE to ~/.bashrc: 'export PXF_BASE=$PXF_BASE'"
+}
+
+# run the migration script on a shell with minimal environment variables loaded
+function migrateMergeConfiguration()
+{
+    env -i "$BASH" -c "PXF_BASE=$PXF_BASE PXF_CONF=$PXF_CONF $PXF_HOME/bin/merge-pxf-config.sh"
+}
+
+# doMigrate migrates old configurations of PXF to a Spring Boot based configuration of PXF
+function doMigrate()
+{
+    # Validate PXF_CONF
+    if [[ -z "$PXF_CONF" ]]; then
+        echoRed    "ERROR: The \$PXF_CONF environment variable is not specified. Specify the \$PXF_CONF location of your old PXF installation"
+        echoYellow "HINT:  Use 'PXF_CONF=<YOUR_PXF_CONF_DIRECTORY> [PXF_BASE=<YOUR_PXF_BASE_DIRECTORY>] pxf [cluster] migrate'."
+        exit 1
+    fi
+
+    # Make sure $PXF_CONF/conf/pxf-env.sh is present
+    [[ ! -f "${PXF_CONF}/conf/pxf-env.sh" ]]       && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/conf/pxf-env.sh' file is missing"
+    # Make sure $PXF_CONF/conf/pxf-profiles.xml is present
+    [[ ! -f "${PXF_CONF}/conf/pxf-profiles.xml" ]] && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/conf/pxf-profiles.xml' file is missing"
+    [[ ! -d "${PXF_CONF}/servers" ]]               && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/servers' directory is missing"
+    [[ ! -d "${PXF_CONF}/lib" ]]                   && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/lib' directory is missing"
+    [[ ! -d "${PXF_CONF}/keytabs" ]]               && fail "Invalid \$PXF_CONF location. The '${PXF_CONF}/keytabs' directory is missing"
+
+    # FILE1 -ef FILE2  True if file1 is a hard link to file2.
+    [[ "$PXF_CONF" -ef "$PXF_BASE" ]] && fail "The \$PXF_CONF directory must be different from your target directory '$PXF_BASE'"
+
+    # Validate PXF_BASE
+    [[ ! -f "${PXF_BASE}/conf/pxf-env.sh" ]]                 && fail "Invalid \$PXF_BASE location. The '${PXF_BASE}/conf/pxf-env.sh' file is missing"
+    [[ ! -f "${PXF_BASE}/conf/pxf-application.properties" ]] && fail "Invalid \$PXF_BASE location. The '${PXF_BASE}/conf/pxf-application.properties' file is missing"
+    [[ ! -f "${PXF_BASE}/conf/pxf-log4j2.xml" ]]             && fail "Invalid \$PXF_BASE location. The '${PXF_BASE}/conf/pxf-log4j2.xml' file is missing"
+
+    echoGreen ""
+    echoGreen "Starting \$PXF_CONF migration from '${PXF_CONF}' to '${PXF_BASE}'"
+    echoGreen "Copying the pxf-profiles.xml file to '${PXF_BASE}/conf'"
+    cp -L "${PXF_CONF}/conf/pxf-profiles.xml" "${PXF_BASE}/conf"
+    echoGreen "Copying the servers, lib, and keytabs directories to '${PXF_BASE}'"
+    cp -LR "${PXF_CONF}/servers" "${PXF_CONF}/lib" "${PXF_CONF}/keytabs" "${PXF_BASE}"
+    echoGreen "Merging values from '${PXF_CONF}/conf/pxf-env.sh' to '${PXF_BASE}/conf/pxf-application.properties' and '${PXF_BASE}/conf/pxf-env.sh'"
+    migrateMergeConfiguration
+    echoGreen "PXF migration completed successfully. Migrated from '${PXF_CONF}' to '${PXF_BASE}'"
+    echoGreen "NOTE: Any customizations to your pxf-log4j.properties file will need to be manually migrated."
 }
 
 #
@@ -457,7 +503,7 @@ case $pxf_script_command in
         ;;
     'register')
         installExternalTableExtension
-	;;
+        ;;
     'start')
         doStart
         ;;
@@ -492,6 +538,9 @@ case $pxf_script_command in
         ;;
     'prepare')
         doPrepare "$@"
+        ;;
+    'migrate')
+        doMigrate "$@"
         ;;
     *)
         printUsage
