Deprecate PXF init and reset commands
Stop copying pxf-profiles-default.xml to conf

The pxf-profiles-default.xml file can be loaded from resources instead
of a file. This reduces the duplicate existence of this file. We no
longer provide a physical file for pxf-profiles-default.xml

Rename management.health.probes.enabled to management.endpoint.health.probes.enabled

The property name changed from management.health.probes.enabled to
management.endpoint.health.probes.enabled. This commit no longer uses
the deprecated property name

Remove redundant properties from pxf-env-default.sh

PXF_CONNECTION_TIMEOUT, PXF_MAX_THREADS, PXF_FRAGMENTER_CACHE are
properties that have already been defined in the application.properties
file, and are redundant. We prefer application.properties over
environment variables for these properties.

Also, we no longer need to add files from the $PXF_HOME/conf classpath,
as the files in the conf directory are going away.

Allow configuring logging.file.name property

Spring Boot exposes the logging.file.name. We take advantage of this
property and use it for the pxf-log4j2.xml file. We still default to
$PXF_LOGDIR/pxf-service.log for the logging.file.name

Add PXF banner

Inline pxf-env-default.sh inside pxf

The pxf-env-default.sh file no longer needs to be it's own script and
can be merged with the main pxf script. Because `pxf-env-default.sh`
values don't change, we can merge these two scripts

Remove nesting in templates and copy to final target

Remove the unnecessary additional nesting for the templates directory.
We now install the templates into its final destination under $PXF_HOME
by default.

Provide a run directory by default

Don't create the run directory during pxf init, but provide the run
directory by default

Create the keytab directory during stage

Create the lib directory

Create the lib directory, and rename the existing `$PXF_HOME/lib`
directory to `$PXF_HOME/share`.

Split configuration files into pxf-application.configuration

Configuration files are now split into pxf-application.configuration

Rename PXF_CONF directory to PXF_RUN

The PXF_RUN directory now defaults to PXF_HOME. pxf init is not a
requirement to start PXF.

pxf register now only copies the control file

Only copy the control file during pxf register and update the directory
and module_pathname to point to the extension directory inside
$PXF_HOME.

Small change in Makefile

Rename PXF_CONF_DIR to PXF_RUN_DIR

Rename PXF_CONF_DIR to PXF_RUN_DIR and default it to PXF_HOME. Also,
remove the initialization process in PXF and replace it with the pxf
register command.

Rename PXF_CONF -> PXF_RUN in Dockerfiles

Rename PXF_CONF -> PXF_RUN in docker files and default the value to the
same value as PXF_HOME

PXF_CONF -> PXF_RUN in automation code

The automation Makefile uses PXF_CONF, use PXF_RUN now and default it to
PXF_HOME

Fix automation code to create additional files

RPM: create logs, run directory with the correct attributes during RPM install

Update README and some comments referring to PXF_CONF

PXF_CONF -> PXF_RUN in regression

PXF_CONF -> PXF_RUN in fdw

PXF_CONF -> PXF_RUN in dev

Copy configuration files to PXF_RUN/conf during automation

Fix copying of configuration files to the $PXF_RUN/conf directory

Fix automation tests for clouds

PXF_HOME to PXF_RUN

Update README.md

PXF_CONF -> PXF_RUN in multinode servers

lib is now share

mkdir instead of pre-created dirs

keytabs are in

Move jar from server to application

keytabs are in

fixup! Move jar from server to application

do not chown ~gpadmin/pxf dir

Register the extension on multinode setup

diff --git a/server/pxf-service/src/scripts/pxf b/server/pxf-service/src/scripts/pxf
--- a/server/pxf-service/src/scripts/pxf
+++ b/server/pxf-service/src/scripts/pxf
@@ -37,19 +37,45 @@ parent_script_dir="$( (cd "$( dirname "${script_file}" )/.." && pwd -P) )"
 cd "$WORKING_DIR" || exit 1
 
 # establish PXF_HOME and global vars used by all commands
-export PXF_HOME=$parent_script_dir
+export PXF_HOME=${parent_script_dir}
+
+# Path to PXF_RUN directories, defaults to PXF_HOME
+export PXF_RUN=${PXF_RUN:=$PXF_HOME}
+
+[[ -f ${PXF_RUN}/conf/pxf-env.sh ]] && source "${PXF_RUN}/conf/pxf-env.sh"
+
+# Path to HDFS native libraries
+export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${PXF_RUN}/lib/native:/usr/lib/hadoop/lib/native
+
+# Path to JAVA
+export JAVA_HOME=${JAVA_HOME:=/usr/java/default}
+
+# Path to Log directory
+export PXF_LOGDIR=${PXF_LOGDIR:=${PXF_RUN}/logs}
+
+# Path to Run directory
+export PXF_RUNDIR=${PXF_RUNDIR:=${PXF_RUN}/run}
+
+# Port
+export PXF_PORT=${PXF_PORT:=5888}
+
+# Memory
+export PXF_JVM_OPTS=${PXF_JVM_OPTS:='-Xmx2g -Xms1g'}
+
+# Set to true to enable Remote debug via port 2020
+export PXF_DEBUG=${PXF_DEBUG:-false}
+
+# Kill PXF on OutOfMemoryError, set to false to disable
+export PXF_OOM_KILL=${PXF_OOM_KILL:-true}
+
+# Additional locations to be class-loaded by the application
+export LOADER_PATH="${PXF_LOADER_PATH:+$PXF_LOADER_PATH,}file:${PXF_RUN}/conf,file:${PXF_RUN}/lib"
+
 [[ -z "$STOP_WAIT_TIME" ]] && STOP_WAIT_TIME="60"
-identity="pxf-service"
+identity="pxf-app"
 
-jarfile="${PXF_HOME}/server/pxf-service-_PXF_VERSION_.jar"
-default_env_script=${PXF_HOME}/conf/pxf-env-default.sh
-server_templates=${PXF_HOME}/templates/server-templates/
-
-SED_OPTS=(-i)
-if [[ $OSTYPE == "darwin"* ]]; then
-    SED_OPTS+=("")
-fi
-SED_OPTS+=(-e)
+jarfile="${PXF_HOME}/application/pxf-app-_PXF_VERSION_.jar"
+pid_file="${PXF_RUNDIR}/${identity}.pid"
 
 # ANSI Colors
 echoRed() { echo $'\e[0;31m'"$1"$'\e[0m'; }
@@ -61,72 +87,16 @@ function validate_user()
     [[ $EUID == 0 ]] && fail 'Cannot run as root user'
 }
 
-function confirm_with_user()
+function checkPermissions()
 {
-    echoGreen  '*****************************************************************************'
-    echoGreen  '* The PXF_CONF variable is not defined, using default location'
-    echoGreen  "* Using ${PXF_CONF} for user configurations"
-    echoYellow '* WARNING: using this directory is not recommended for production deployments'
-    echoGreen  '*****************************************************************************'
-
-    read -rp 'Do you want to proceed? [Y]: ' answer
-    answer=${answer:-'Y'}
-    case ${answer:0:1} in
-        y|Y)
-            echoGreen 'Proceeding with the initialization'
-        ;;
-        *)
-            echoYellow 'Initialization aborted'
-            exit 1
-        ;;
-    esac
-}
-
-function update_pxf_conf()
-{
-    if [[ -z $PXF_CONF ]]; then
-        # PXF_CONF was not specified during init command
-        # need to default to user's home directory and ask for confirmation, unless silent mode is used
-        local current_user pxf_user_home
-        current_user=$( id -un )
-        pxf_user_home=$HOME
-        if [[ -z $pxf_user_home ]]; then
-            fail "PXF_CONF is not set and user $current_user home directory is not defined"
-        elif [[ ! -d ${pxf_user_home} ]]; then
-            fail "PXF_CONF is not set and user $current_user home directory $pxf_user_home does not exist"
-        else
-            export PXF_CONF=${pxf_user_home}/pxf
-            if [[ $silent == false ]]; then
-                confirm_with_user
-            fi
-        fi
-    fi
-
-    echoYellow "Using $PXF_CONF as a location for user-configurable files"
-
-    # update the value on PXF_CONF in the default env file
-    sed "${SED_OPTS[@]}" "s|{PXF_CONF:-.*}$|{PXF_CONF:-\"${PXF_CONF}\"}|g" "$default_env_script"
-}
-
-function getEnvironment()
-{
-    local USER_SPECIFIED_JAVA_HOME=${JAVA_HOME}
-    # load default environment
-    if [[ ! -f $default_env_script ]]; then
-        fail "Failed to find $default_env_script"
-    fi
-    # shellcheck source=/Users/pivotal/workspace/pxf/server/pxf-service/src/scripts/pxf-env-default.sh
-    source "$default_env_script"
-    # we may have just overridden the user's intended JAVA_HOME
-    # by sourcing PXF_CONF/conf/pxf-env.sh
-    [[ ${PRESERVE_JAVA_HOME} == true ]] && JAVA_HOME=${USER_SPECIFIED_JAVA_HOME}
-    pid_file="$PXF_RUNDIR/${identity}.pid"
+    touch "$pid_file" &> /dev/null || { echoRed "ERROR: Operation not permitted (cannot access pid file: '$pid_file')"; return 4; }
+    [[ -d "$PXF_LOGDIR" ]] || { echoRed "ERROR: Operation not permitted (log directory does not exist: '$PXF_LOGDIR')"; return 4; }
 }
 
 function checkJavaHome()
 {
     # Find Java
-    [[ -x ${JAVA_HOME}/bin/java ]] || fail "\$JAVA_HOME=$JAVA_HOME is invalid. Set \$JAVA_HOME in your environment before initializing PXF."
+    [[ -x ${JAVA_HOME}/bin/java ]] || fail "\$JAVA_HOME=$JAVA_HOME is invalid. Set \$JAVA_HOME in your environment before running PXF commands."
     javaexe="$JAVA_HOME/bin/java"
 }
 
@@ -183,69 +153,6 @@ function isRunning() {
     ps -p "$1" &> /dev/null
 }
 
-function checkPermissions() {
-    touch "$pid_file" &> /dev/null || { echoRed "ERROR: Operation not permitted (cannot access pid file)"; return 4; }
-}
-
-function createLogsDir()
-{
-    # logs dir is likely outside PXF_HOME, setup only if it does not yet exist
-    if [[ ! -d $PXF_LOGDIR ]]; then
-        echoGreen "Creating PXF logs directory $PXF_LOGDIR ..."
-        mkdir -p "$PXF_LOGDIR"
-        chmod 700 "$PXF_LOGDIR"
-    fi
-}
-
-function createRunDir()
-{
-    echoGreen "Creating PXF runtime directory $PXF_RUNDIR ..."
-    mkdir -p "$PXF_RUNDIR"
-    chmod 700 "$PXF_RUNDIR"
-}
-
-function generateUserConfigs()
-{
-    # create and setup user configuration directories (only if they do not exist)
-    setup_conf_directory "${PXF_CONF}"
-    setup_conf_directory "${PXF_CONF}/conf" "${PXF_HOME}/templates/user/conf"
-    setup_conf_directory "${PXF_CONF}/keytabs"
-    setup_conf_directory "${PXF_CONF}/lib"
-    setup_conf_directory "${PXF_CONF}/servers"
-    setup_conf_directory "${PXF_CONF}/lib/native"
-    setup_conf_directory "${PXF_CONF}/servers/default"
-    setup_conf_directory "${PXF_CONF}/templates" "${PXF_HOME}/templates/user/templates" 'override'
-
-    if [[ ! -f "${PXF_CONF}/conf/pxf-log4j2.xml" ]]; then
-        # copy the new pxf-log4j2.xml if it doesn't exist. This allows us to
-        # initialize PXF 6.x using a pre-existing PXF 5.x configuration
-        cp "${PXF_HOME}/templates/user/conf/pxf-log4j2.xml" "${PXF_CONF}/conf/pxf-log4j2.xml"
-    fi
-}
-
-function setup_conf_directory()
-{
-    local target=$1
-    local source=$2
-    local override=$3
-
-    if [[ ! -d $target ]]; then
-        if [[ -z $source ]]; then
-            echoGreen "Creating configuration directory $target ..."
-            mkdir -p "$target"
-        else
-            echoGreen "Copying configurations from $source to $target ..."
-            cp -R "$source" "$(dirname "$target")"
-        fi
-    elif [[ -n $source && -n $override ]]; then
-        echoGreen "Updating configurations from $source to $target ..."
-        cp -R "$source" "$(dirname "$target")"
-    else
-        echoGreen "Directory $target already exists, no update required"
-        return 0
-    fi
-}
-
 function validate_system()
 {
     # validate curl
@@ -263,7 +170,7 @@ function printUsage()
 	${bold}NAME${normal}
 	    pxf - manage a single PXF instance or a PXF cluster
 
-	${bold}usage${normal}:  pxf <command> [-y]
+	${bold}usage${normal}:  pxf <command>
 	        pxf cluster <command>
 	        pxf {-h | --help}
 	EOF
@@ -278,21 +185,21 @@ doHelp() {
     cat <<-EOF
 
 	${bold}List of commands${normal}:
-	  init                initialize the local PXF server instance, install PXF extension under \$GPHOME
 	  start               start the local PXF server instance
 	  stop                stop the local PXF server instance
 	  restart             restart the local PXF server instance (not supported for cluster)
 	  status              show the status of the local PXF server instance
 	  version             show the version of PXF server
-	  reset               undo the local PXF initialization
 	  register            install PXF extension under \$GPHOME (useful after upgrades of Greenplum server)
 	  cluster <command>   perform <command> on all the segment hosts in the cluster; try ${bold}pxf cluster help$normal
 
-	  sync <hostname>     synchronize \$PXF_CONF/{conf,lib,servers} directories onto <hostname>. Use --delete to delete extraneous remote files
+	  sync <hostname>     synchronize \$PXF_RUN/{conf,lib,servers} directories onto <hostname>. Use --delete to delete extraneous remote files
+
+	  init                ${bold}(deprecated)${normal} install PXF extension under \$GPHOME
+	  reset               ${bold}(deprecated)${normal} no operation
 
 	${bold}Options${normal}:
 	  -h, --help    show command help
-	  -y            answer yes, use default PXF_CONF=\$HOME/pxf user configuration directory
 	EOF
     exit 0
 }
@@ -306,33 +213,11 @@ function promptUser() {
 # doReset handles the reset command
 function doReset()
 {
-    local force=$2
-    echoRed "This is a destructive action!"
-
-    if [[ -f "$pid_file" ]]; then
-        pid=$(cat "$pid_file")
-        isRunning "$pid" && { echoYellow "PXF is running [pid=$pid]"; }
-    fi
-
-    local prompt='Ensure your local PXF instance is stopped before continuing.
-    Press [y] to continue:'
-    if [[ $force != -f && $force != --force ]] && ! promptUser "$prompt"; then
-        echoYellow 'pxf reset cancelled'
-        return 1
-    fi
-
-    if doStatus > /dev/null; then
-        fail "PXF is running. Stop PXF before running 'pxf [cluster] reset'"
-    fi
-
-    echoYellow "Ignoring ${PXF_CONF}..."
-    echoYellow "Cleaning ${PXF_RUNDIR}..."
-    rm -rf "$PXF_RUNDIR"
-
-    echoYellow "Reverting changes to ${default_env_script}..."
-    sed "${SED_OPTS[@]}" "s|{PXF_CONF:-\".*\"}|{PXF_CONF:-NOT_INITIALIZED}|g" "$default_env_script"
-
-    echoGreen "Finished resetting PXF"
+    echoYellow '*****************************************************************************'
+    echoYellow '* DEPRECATION NOTICE:'
+    echoYellow '* The "pxf [cluster] reset" command is deprecated and will be removed'
+    echoYellow '* in a future release of PXF.'
+    echoYellow '*****************************************************************************'
 }
 
 function installExternalTableExtension()
@@ -343,8 +228,11 @@ function installExternalTableExtension()
         elif [[ ! -f ${GPHOME}/greenplum_path.sh ]]; then
             echoYellow "WARNING: environment variable GPHOME (${GPHOME}) must be set to a valid Greenplum installation, skipping install of Greenplum External Table PXF Extension'"
         else
-            echoGreen "Installing Greenplum External Table PXF Extension into ${GPHOME}"
-            cp -av ${parent_script_dir}/gpextable/* ${GPHOME}
+            echoGreen "Installing Greenplum External Table PXF Extension into '${GPHOME}'"
+
+            local target_control_file="${GPHOME}/share/postgresql/extension/pxf.control"
+            cp -Lv "${parent_script_dir}/gpextable/pxf.control" "${target_control_file}"
+            chmod 644 "${target_control_file}"
         fi
     fi
 }
@@ -352,25 +240,16 @@ function installExternalTableExtension()
 # doInit handles the init command
 function doInit()
 {
-    if ! grep 'PXF_CONF:-NOT_INITIALIZED' "$default_env_script" > /dev/null; then
-        echoYellow "PXF has already been initialized. Use 'pxf [cluster] reset' before attempting to re-initialize PXF"
-        return 1
-    fi
-
-    update_pxf_conf
-    # preserve JAVA_HOME in case user is trying to change it
-    PRESERVE_JAVA_HOME=true getEnvironment
+    echoYellow '*****************************************************************************'
+    echoYellow '* DEPRECATION NOTICE:'
+    echoYellow '* The "pxf [cluster] init" command is deprecated and will be removed'
+    echoYellow '* in a future release of PXF.'
+    echoYellow '*'
+    echoYellow '* Use the "pxf [cluster] register" command instead.'
+    echoYellow '*'
+    echoYellow '*****************************************************************************'
     checkJavaHome
-    generateUserConfigs || return 1
-    editPxfEnvSh || return 1
-    createLogsDir || return 1
-    createRunDir  || return 1
     installExternalTableExtension || return 1
-}
-
-function editPxfEnvSh()
-{
-    sed "${SED_OPTS[@]}" "s|.*JAVA_HOME=.*|JAVA_HOME=${JAVA_HOME}|g" "${PXF_CONF}/conf/pxf-env.sh"
 }
 
 #
@@ -382,8 +261,6 @@ function editPxfEnvSh()
 #
 function doStart()
 {
-    getEnvironment
-    checkPxfConf
     checkJavaHome
     warnUserEnvScript
     do_start
@@ -395,17 +272,27 @@ function do_start() {
         isRunning "$pid" && { echoYellow "PXF is already running [pid=$pid]"; return 0; }
     fi
 
-    PXF_OPTS=(-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlogging.config=${PXF_CONF}/conf/pxf-log4j2.xml)
+    PXF_OPTS=(-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlogging.config=${PXF_RUN}/conf/pxf-log4j2.xml)
     [[ $PXF_DEBUG == true ]]      && PXF_OPTS+=(-agentlib:jdwp=transport=dt_socket,address=2020,suspend=n,server=y)
     [[ $PXF_OOM_KILL = true ]]    && PXF_OPTS+=(-XX:OnOutOfMemoryError="${PXF_HOME}/bin/kill-pxf.sh %p")
     [[ -n "$PXF_OOM_DUMP_PATH" ]] && PXF_OPTS+=(-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$PXF_OOM_DUMP_PATH)
     JAVA_OPTS=($PXF_JVM_OPTS  "${PXF_OPTS[@]}")
+    RUN_ARGS=(--spring.config.location=classpath:/application.properties,file:${PXF_RUN}/conf/pxf-application.properties)
 
     local arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true "${JAVA_OPTS[@]}" -jar "$jarfile" $RUN_ARGS)
 
     working_dir=$(dirname "$jarfile")
     pushd "$working_dir" > /dev/null || exit 1
     checkPermissions || return $?
+
+    echoGreen "Starting PXF with properties:"
+    echoGreen "   JAVA_HOME=${JAVA_HOME}"
+    echoGreen "   PXF_HOME=${PXF_HOME}"
+    echoGreen "   PXF_RUN=${PXF_RUN}"
+    echoGreen "   PXF_LOGDIR=${PXF_LOGDIR}"
+    echoGreen "   PXF_RUNDIR=${PXF_RUNDIR}"
+    echoGreen "   PXF_JVM_OPTS=${PXF_JVM_OPTS}"
+    [[ $PXF_DEBUG == true ]] && echoGreen "   LOADER_PATH=${LOADER_PATH}"
 
     "$javaexe" "${arguments[@]}" >> /dev/null 2>&1 &
     pid=$!
@@ -426,8 +313,6 @@ function do_start() {
 #
 function doStop()
 {
-    getEnvironment
-    checkPxfConf
     checkJavaHome
     warnUserEnvScript
 
@@ -435,7 +320,7 @@ function doStop()
     pushd "$working_dir" > /dev/null
     [[ -f $pid_file ]] || { echoYellow "Not running (pidfile not found). Is PXF running? Stop aborted."; return 0; }
     pid=$(cat "$pid_file")
-    isRunning "$pid" || { echoYellow "Not running (process ${pid}). Removing stale pid file."; rm -f "$pid_file"; return 0; }
+    isRunning "$pid" || { echoYellow "Not running (process ${pid}). Removing stale pid file '$pid_file'."; rm -f "$pid_file"; return 0; }
 
     echoYellow "Stopping PXF [pid=$pid]..."
 
@@ -473,9 +358,7 @@ do_stop() {
 
 function doStatus()
 {
-    getEnvironment
     checkJavaHome
-    checkPxfConf
     warnUserEnvScript
     checkWebapp 1 0 || return 1
     echoGreen "PXF is listening on port $PXF_PORT"
@@ -488,34 +371,23 @@ function doSync()
     if [[ -z $target_host ]]; then
         fail 'A destination hostname must be provided'
     fi
-    getEnvironment
-    checkPxfConf
     warnUserEnvScript
-    rsync -az${DELETE:+ --delete} -e "ssh -o StrictHostKeyChecking=no" "$PXF_CONF"/{conf,lib,servers} "${target_host}:$PXF_CONF"
+    rsync -az${DELETE:+ --delete} -e "ssh -o StrictHostKeyChecking=no" "$PXF_RUN"/{conf,lib,servers} "${target_host}:$PXF_RUN"
 }
 
 function doCluster()
 {
     local pxf_cluster_command=$2 is_init=false
     [[ ${pxf_cluster_command} == init ]] && is_init=true
-    PRESERVE_JAVA_HOME=${is_init} getEnvironment
-    # Go CLI handles unset PXF_CONF when appropriate
-    [[ $PXF_CONF == NOT_INITIALIZED ]] && unset PXF_CONF
+    # Go CLI handles unset PXF_RUN when appropriate
     [[ ${is_init} == false ]] && warnUserEnvScript
     "${parent_script_dir}/bin/pxf-cli" "$@"
 }
 
 function warnUserEnvScript()
 {
-   local user_env_script=${PXF_CONF}/conf/pxf-env.sh
+   local user_env_script=${PXF_RUN}/conf/pxf-env.sh
    [[ -f $user_env_script ]] || echoYellow "WARNING: failed to find ${user_env_script}, default parameters will be used"
-}
-
-function checkPxfConf()
-{
-    if [[ $PXF_CONF == NOT_INITIALIZED ]] || grep 'PXF_CONF:-NOT_INITIALIZED' "$default_env_script" > /dev/null; then
-        fail "PXF is not yet initialized, you must run the 'pxf [cluster] init' command first."
-    fi
 }
 
 pxf_script_command=$1
